version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3009:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  

  node-app:
    build: .
    #ports:
    #  - "3009:3009"

    environment:
      - PORT=3009
    depends_on:
      - mongo  

  mongo:
    image: mongo

    environment:
      - MONGO_INITDB_ROOT_USERNAME=kumar
      - MONGO_INITDB_ROOT_PASSWORD=mypassword 
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    
volumes:
  mongo-db:  




     #volumes:
    # - ./:/app
    # - /app/node_modules 
  
    #  env_file:
    # - ./.env
